### ISSUE TITLE
Error producing bam file for IRMA

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/walkercreek#9]
### Description of the bug

Missing output bam file during ASSEMBLY_TYPING_CLADE_VARIABLES:IRMA (TP20230307)

### Command used and terminal output

```console
nextflow.cli.Launcher - $> nextflow run -r v.2.0.0 UPHL-BioNGS/walkercreek -profile singularity --max_cpus 100 --input samplesheet_orig.csv --outdir 19March2024

Output: see nextflow.log
```

### Relevant files

[nextflow.log](https://github.com/UPHL-BioNGS/walkercreek/files/14669133/nextflow.log)
[errors.txt](https://github.com/UPHL-BioNGS/walkercreek/files/14669134/errors.txt)

### System information

N E X T F L O W  ~  version 23.10.1
Amazon
Singularity
Amazon Linux 2
2.0.0

**Comment by tives82** [comment]
This issue has been corrected with the latest release (v.2.0.1).
